### ISSUE TITLE
Lab 2/22

### ISSUE THREAD

**Issue by sawellons** [Planet-Nine/cs207project#3]
Part 1:  Individual

Part 2:  Individual(?)

Part 3:  Implementing mean and median into timeseries, building tests
We should probably carve out a centralized timeseries.py or .ipynb that we are all building upon together.  As a start, let's take the relevant code from Non Uniform Time and Lazy-v2.ipynb?  Then we will need someone to write the methods and someone to write a test function.

**Comment by rkuade** [comment]
OK the methods are done, you guys can check them over, but a test program is still needed. Also, maybe we should hook the repository up to Travis and Coveralls.

**Comment by sawellons** [comment]
I've now written basic unittests for the mean and median methods, which you can find in test_timeseries.py, and I slightly modified the methods to raise a ValueError if the timeseries has length 0.  Feel free to add more tests (and we still need tests for the iterator methods).
